import React, { createContext, useCallback, useContext, useState } from "react";

// Translation keys for the entire app (Merged)
const translations: Record<string, any> = {
  en: {
    // Navigation
    home: "Home",
    enterData: "Enter Data",
    suggestions: "Suggestions",
    history: "History",
    weather: "Weather",
    disease: "Disease",
    market: "Market",
    changeLanguage: "हिन्दी",

    profile: "Profile",
    profile_subtitle: "Manage your account and farm details",
    user_name: "Name",
    user_email: "Email",
    user_phone: "Phone",
    user_location: "Location",
    farm_info: "Farm Information",
    farm_size: "Farm Size (acres)",
    soil_type: "Soil Type",
    main_crops: "Main Crops",
    experience: "Experience (years)",
    personal_info: "Personal Information",
    edit_profile: "Edit Profile",
    cancel_edit: "Cancel",
    save_changes: "Save Changes",
    logout: "Logout",
    logout_confirm: "Are you sure you want to logout?",
    cancel: "Cancel",
    success_title: "Success",
    profile_updated: "Profile updated successfully!",
    error_title: "Error",
    error_saving_profile: "Failed to save profile.",
    error_loading_profile: "Error loading profile.",
    logout_error: "Logout failed.",
    loading_profile: "Loading profile...",
    user_not_found: "User not found.",

    // Dashboard & General UI (NEW)
    welcomeBack: "Welcome back! 👋",
    quickAccess: "Quick Access",
    smartCropRecommendation: "Smart Crop Recommendation System",
    smartCropSubtitle:
      "Get AI-powered crop suggestions based on your soil and weather conditions",
    uploadPhotoFile: "Upload Photo/File",
    uploadSubtitle: "Auto-detect soil & weather values",
    todaysOverview: "Today's Overview",
    viewAnalytics: "View Analytics",
    analyticsSubtitle: "Check historical yield data and trends",
    pageTitle: "Enter Farm Data",
    pageSubtitle:
      "Provide your soil and weather information for personalized crop recommendations.",
    voice: "Voice",

    // Weather Details
    title: "Weather Forecast",
    subtitle: "Amaravati, AP - Updated",
    sevenDayForecast: "7-Day Weather Forecast",
    todaysWeather: "Today's Weather",
    temperature: "Temperature",
    humidity: "Humidity",
    rainfall: "Rainfall",
    windSpeed: "Wind Speed",
    today: "Today",
    tomorrow: "Tomorrow",
    feelsLike: "Feels like",
    uvIndex: "UV Index",
    todaysForecast: "Today's Forecast",
    threeMonthOutlook: "3-Month Outlook",
    climateAverages: "Climate Averages",
    alerts: "Alerts & Recommendations",
    rain: "Rain",
    avgTemp: "Average Temperature",
    annualRainfall: "Annual Rainfall",
    avgHumidity: "Average Humidity",
    growingSeasons: "Best Growing Seasons",
    winter: "Winter (Nov-Feb)",
    spring: "Spring (Mar-May)",
    postMonsoon: "Post-Monsoon",

    // Crop Recommendations
    cropSuggestionsTitle: "Crop Recommendations",
    cropSuggestionsSubtitle: "AI-powered suggestions based on your farm data",
    analyzingData: "Analyzing your farm data...",
    soilMatch: "Soil Match",
    weatherSuitability: "Weather Suitability",
    yieldPotential: "Yield Potential",
    duration: "Duration",
    waterRequirement: "Water Requirement",
    totalYield: "Expected Yield",
    whyThisCrop: "Why this crop?",
    matchPercentage: "Match",
    highYield: "High",
    mediumYield: "Medium",
    lowYield: "Low",
    highWater: "High",
    mediumWater: "Medium",
    lowWater: "Low",
    tons: "tons",
    phLevel: "pH Level",
    nitrogen: "Nitrogen (N)",
    phosphorus: "Phosphorus (P)",
    potassium: "Potassium (K)",
    overallGood: "Overall: Good",

    // Form inputs
    landSize: "Land Size",
    soilType: "Soil Type",
    climateCondition: "Climate Condition",
    irrigationAvailable: "Irrigation Available",

    // Disease Detection
    diseaseTitle: "Disease Detection",
    diseaseSubtitle:
      "Upload a crop image and describe the issue for AI-powered analysis.",
    uploadPlaceholder: "No image uploaded yet",
    fromGallery: "From Gallery",
    useCamera: "Use Camera",
    describePlaceholder:
      "Describe the problem (e.g., yellow spots, wilting leaves)",
    analyzeButton: "Analyze Crop Health",
    analyzing: "Analyzing...",
    resultTitle: "AI Analysis Result",
    upload: "Upload",

    // Voice commands
    voiceNotAvailable: "Voice feature not available here.",
    startRecording: "Start Recording",
    stopRecording: "Stop Recording",
    speakWeb: "Speak",
    stopWeb: "Stop",
    webVoice: "Web voice",
    mobileVoice: "Mobile voice → server transcription",

    // Alerts & Permissions (NEW & Merged)
    failweather: "Failed to fetch weather data",
    weatherAlert: "Weather Alert",
    rainAlert:
      "Rain expected in the next 3 days. Consider adjusting irrigation.",
    fetchingLocation: "Fetching location...",
    loadingWeather: "Loading weather data...",
    unknownLocation: "Unknown Location",
    locationPermissionDenied:
      "Permission to access location was denied. Showing default location.",
    couldNotGetLocation: "Could not get current location. Showing default.",
    permissionRequired: "Permission Required",
    errorTitle: "Error",
    couldNotFetchLocation: "Could not fetch current location.",
    enterLocationTitle: "Enter Location",
    enterCityName: "Please enter a city name:",
    notFoundTitle: "Not Found",
    couldNotFindLocation: "Could not find location: ",
    failedToSearchLocation: "Failed to search for location.",
    successTitle: "Success",
    fileSelected: "File selected: ",
    cameraAccessRequired: "Camera access is required to take photos.",
    photoCaptured: "Photo captured successfully!",
    missingImage: "Please upload an image before analyzing.",
    grantPermission: "Please grant camera/library permission.",
    grantMicPermission: "Please grant microphone permission.",
    camera1: "Camera",
    welcome: "Welcome Back",

    // Soil Properties Card
    soilProperties: "Soil Properties",
    soilColor: "Soil Type",
    selectSoilColor: "Select soil type",
    acidic: "Acidic",
    neutral: "Neutral",
    alkaline: "Alkaline",
    sulfur: "Sulfur (S)",
    zinc: "Zinc (Zn)",

    // Weather Info Card
    weatherInfo: "Weather Information",
    fetchWeather: "Fetch Live Weather Data",
    fetchingWeather: "Fetching...",
    currentSeason: "Current Season",
    selectCurrentSeason: "Select current season",

    // Climate Data Card
    climateData: "Climate Data",
    groundwaterLevel: "Ground Water Level",
    selectGroundwater: "Select groundwater level",
    cloudCoverage: "Cloud Coverage",
    surfacePressure: "Surface Pressure",

    // Farm Details Card
    farmDetails: "Farm Details",
    enterLandSize: "Enter land size in acres",

    // Actions and Modals
    submit: "Submit Data & Get Recommendations",
    listening: "Listening...",
    voiceInstructions: 'Try saying: "Set nitrogen to 70 and temperature to 25"',

    // Picker Options
    soilColorAlluvial: "Alluvial",
    soilColorBlack: "Black",
    soilColorRed: "Red",
    seasonMonsoon: "Monsoon (Kharif)",
    seasonSummer: "Summer (Zaid)",
    seasonWinter: "Winter (Rabi)",
    groundwaterHigh: "High",
    groundwaterMedium: "Medium",
    groundwaterLow: "Low",

    // General
    loading: "Loading...",
    error: "Error",
    success: "Success",
    retry: "Retry",
    back: "Back",
    next: "Next",
    goToDiseaseDetection: "Go to Disease Detection",
    identifyCropDiseases: "Identify crop diseases instantly",
    soilCondition: "Soil Condition",

    // --- Crop Recommendations Page ---
    filterRecommendations: "Filter Recommendations",
    allCrops: "All Crops",
    shortDuration: "Short Duration",
    fertilizerRecommendations: "Recommend Fertilizers",
    forCrop: "for",
    productionBoost: "Production Boost",
    diseaseControl: "Disease Control",
    weedManagement: "Weed Management (Grass Killer)",
    dosage: "Dosage",
    notes: "Notes",
    close: "Close",

    weatherForecast: "Weather Forecast",
    updated: "Updated",

    alertsAndRecommendations: "Alerts & Recommendations",
    // Data-specific translations
    overcast: "Overcast",
    low: "Low",
    moderate: "Moderate",
    high: "High",
    veryHigh: "Very High",
    extreme: "Extreme",
    // Outlooks
    october: "October",
    retreatingMonsoon: "Retreating Monsoon",
    retreatingMonsoonDesc:
      "Northeast monsoon brings risk of heavy rainfall and cyclonic activity from the Bay of Bengal.",
    november: "November",
    activeCyclone: "Active Cyclone Season",
    activeCycloneDesc:
      "Peak cyclone season for the region. Monitor updates for potential storms and heavy winds.",
    december: "December",
    coolPleasant: "Cool & Pleasant",
    coolPleasantDesc:
      "Monsoon activity subsides, transitioning to cooler, drier winter weather.",
    heavyRain: "Heavy Rain",
    potentialFloods: "Potential Floods",
    storms: "Storms",
    morningFog: "Morning Fog",
    // Alerts
    rainExpected: "Rain Expected",
    rainExpectedDesc:
      "Heavy rainfall predicted for Wednesday. Consider adjusting irrigation schedule and protect sensitive crops.",
    highUV: "High UV Index",
    highUVDesc:
      "UV levels will be high this weekend. Ensure adequate protection for workers and consider shade covers.",
    optimalConditions: "Optimal Growing Conditions",
    optimalConditionsDesc:
      "Temperature and humidity levels are ideal for most crops. Good time for planting and field activities.",
    title1: "Historical Data",
    subtitle1: "Track and analyze your farm's performance over time",
    overview: "Overview",
    records: "Records",
    analytics: "Analytics",
    totalArea: "Total Area Farmed",
    avgYield: "Avg. Yield / Acre",
    totalProd: "Total Production",
    cropsRecorded: "Crops Recorded",
    bestCrops: "Best Performing Crops",
    quintals: "quintals",
    acres: "acres",
    yieldPerAcre: "q/acre",
    sown: "Sown",
    harvested: "Harvested",
    area: "Area",
    irrigationEff: "Irrigation Efficiency Analysis",
    yieldPerformance: "Yield Performance by Crop",
    rainfallTrend: "Rainfall vs Crop Yield Trend",
    crop: "Crop",

    yield: "Yield (q)",

    avgPH: "Average pH",
    avgNitro: "Average Nitrogen (kg/ha)",

    market_title: "Harvest & Market Prices",
    market_subtitle: "Get current market prices and selling recommendations",
    market_cropType: "Crop Type",
    market_harvestQuantity: "Harvest Quantity (Quintals)",
    market_getCurrentPrices: "Get Current Prices",
    market_priceAnalysis: "Price Analysis",
    market_recommendedPrice: "Recommended Selling Price",
    market_currentPrice: "Current Market Price",
    market_weekHigh: "Week High",
    market_weekLow: "Week Low",
    market_trend: "Trend",
    market_totalValue: "Total Value",
    market_sellNow: "Sell Now",
    market_waitAdvice: "Wait for Better Price",
    market_priceUp: "Price Rising",
    market_priceDown: "Price Falling",
    market_stable: "Stable",
    market_bestTime: "Best time to sell",
    market_waitTime: "Consider waiting 2-3 days",
    market_selectCrop: "Select a crop",
    market_enterQuantity: "Enter quantity",
    market_last7Days: "Last 7 Days Prices",
    market_date: "Date",
    market_price: "Price",
    market_recommendation: "Selling Recommendation",
    market_rupees: "₹",
    market_per: "per",
    market_quintal: "quintal",
    market_crops: {
      wheat: "Wheat",
      rice: "Rice",
      corn: "Corn/Maize",
      cotton: "Cotton",
    },
    loginWelcome: "Welcome to",
    loginAppName: "KrishiMitra",
    loginSubtitle: "Your Smart Agricultural Intelligence Platform",
    loginEmailSectionTitle: "Login with Email",
    loginEmailPlaceholder: "Enter your email",
    loginPasswordPlaceholder: "Enter your password",
    loginButtonText: "Login",
    loginGoogleButton: "Continue with Google",
    loginGuestButton: "Continue as Guest",
    loginForgotPassword: "Forgot Password?",
    loginNoAccount: "Don't have an account?",
    loginSignUpLink: "Sign Up",
    loginOrContinueWith: "Or continue with",
    loginErrorInvalidCredentials: "Invalid email or password",
    loginSuccessMessage: "Login successful!",
  },
  te: {
    "home": "హోమ్",
    "enterData": "డేటా నమోదు చేయండి",
    "suggestions": "సూచనలు",
    "history": "చరిత్ర",
    "weather": "వాతావరణం",
    "disease": "వ్యాధి",
    "market": "మార్కెట్",
    "changeLanguage": "తెలుగు",
    "profile": "ప్రొఫైల్",
    "profile_subtitle": "మీ ఖాతా మరియు వ్యవసాయ వివరాలను నిర్వహించండి",
    "user_name": "పేరు",
    "user_email": "ఈమెయిల్",
    "user_phone": "ఫోన్",
    "user_location": "స్థానం",
    "farm_info": "వ్యవసాయ సమాచారం",
    "farm_size": "వ్యవసాయ పరిమాణం (ఎకరాలు)",
    "soil_type": "మట్టి రకం",
    "main_crops": "ప్రధాన పంటలు",
    "experience": "అనుభవం (సంవత్సరాలు)",
    "personal_info": "వ్యక్తిగత సమాచారం",
    "edit_profile": "ప్రొఫైల్ సవరించండి",
    "cancel_edit": "రద్దు చేయండి",
    "save_changes": "మార్పులను సేవ్ చేయండి",
    "logout": "లాగౌట్",
    "logout_confirm": "మీరు నిజంగా లాగౌట్ చేయాలనుకుంటున్నారా?",
    "cancel": "రద్దు చేయండి",
    "success_title": "విజయం",
    "profile_updated": "ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!",
    "error_title": "లోపం",
    "error_saving_profile": "ప్రొఫైల్ సేవ్ చేయడంలో విఫలమైంది.",
    "error_loading_profile": "ప్రొఫైల్ లోడ్ చేయడంలో లోపం.",
    "logout_error": "లాగౌట్ విఫలమైంది.",
    "loading_profile": "ప్రొఫైల్ లోడ్ అవుతోంది...",
    "user_not_found": "వినియోగదారు కనుగొనబడలేదు.",
    "welcomeBack": "స్వాగతం! 👋",
    "quickAccess": "త్వరిత యాక్సెస్",
    "smartCropRecommendation": "స్మార్ట్ పంట సిఫార్సు వ్యవస్థ",
    "smartCropSubtitle": "మీ మట్టి మరియు వాతావరణ పరిస్థితుల ఆధారంగా AI-ఆధారిత పంట సూచనలను పొందండి",
    "uploadPhotoFile": "ఫోటో/ఫైల్ అప్‌లోడ్ చేయండి",
    "uploadSubtitle": "మట్టి & వాతావరణ విలువలను ఆటో-డిటెక్ట్ చేయండి",
    "todaysOverview": "నేటి అవలోకనం",
    "viewAnalytics": "విశ్లేషణలను చూడండి",
    "analyticsSubtitle": "చారిత్రక దిగుబడి డేటా మరియు పోకడలను తనిఖీ చేయండి",
    "pageTitle": "వ్యవసాయ డేటాను నమోదు చేయండి",
    "pageSubtitle": "వ్యక్తిగతీకరించిన పంట సిఫార్సుల కోసం మీ మట్టి మరియు వాతావరణ సమాచారాన్ని అందించండి.",
    "voice": "వాయిస్",
    "title": "వాతావరణ సూచన",
    "subtitle": "అమరావతి, AP - నవీకరించబడింది",
    "sevenDayForecast": "7-రోజుల వాతావరణ సూచన",
    "todaysWeather": "నేటి వాతావరణం",
    "temperature": "ఉష్ణోగ్రత",
    "humidity": "తేమ",
    "rainfall": "వర్షపాతం",
    "windSpeed": "గాలి వేగం",
    "today": "నేడు",
    "tomorrow": "రేపు",
    "feelsLike": "అనిపిస్తుంది",
    "uvIndex": "UV సూచిక",
    "todaysForecast": "నేటి సూచన",
    "threeMonthOutlook": "3-నెలల దృక్పథం",
    "climateAverages": "వాతావరణ సగటులు",
    "alerts": "హెచ్చరికలు & సిఫార్సులు",
    "rain": "వర్షం",
    "avgTemp": "సగటు ఉష్ణోగ్రత",
    "annualRainfall": "వార్షిక వర్షపాతం",
    "avgHumidity": "సగటు తేమ",
    "growingSeasons": "ఉత్తమ పెరుగుతున్న సీజన్లు",
    "winter": "చలికాలం (నవం-ఫిబ్రవరి)",
    "spring": "వసంతకాలం (మార్చి-మే)",
    "postMonsoon": "రుతుపవనాల తర్వాత",
    "cropSuggestionsTitle": "పంట సిఫార్సులు",
    "cropSuggestionsSubtitle": "మీ వ్యవసాయ డేటా ఆధారంగా AI-ఆధారిత సూచనలు",
    "analyzingData": "మీ వ్యవసాయ డేటాను విశ్లేషిస్తోంది...",
    "soilMatch": "మట్టి సరిపోలిక",
    "weatherSuitability": "వాతావరణ అనుకూలత",
    "yieldPotential": "దిగుబడి అవకాశం",
    "duration": "వ్యవధి",
    "waterRequirement": "నీటి అవసరం",
    "totalYield": "ఆశించిన దిగుబడి",
    "whyThisCrop": "ఈ పంట ఎందుకు?",
    "matchPercentage": "సరిపోలిక",
    "highYield": "అధికం",
    "mediumYield": "మధ్యస్థం",
    "lowYield": "తక్కువ",
    "highWater": "అధికం",
    "mediumWater": "మధ్యస్థం",
    "lowWater": "తక్కువ",
    "tons": "టన్నులు",
    "phLevel": "pH స్థాయి",
    "nitrogen": "నత్రజని (N)",
    "phosphorus": "భాస్వరం (P)",
    "potassium": "పొటాషియం (K)",
    "overallGood": "మొత్తం: బాగుంది",
    "landSize": "భూమి పరిమాణం",
    "soilType": "మట్టి రకం",
    "climateCondition": "వాతావరణ పరిస్థితి",
    "irrigationAvailable": "నీటిపారుదల అందుబాటులో ఉంది",
    "diseaseTitle": "వ్యాధి గుర్తింపు",
    "diseaseSubtitle": "AI-ఆధారిత విశ్లేషణ కోసం పంట చిత్రాన్ని అప్‌లోడ్ చేసి, సమస్యను వివరించండి.",
    "uploadPlaceholder": "ఇంకా ఇమేజ్ అప్‌లోడ్ చేయబడలేదు",
    "fromGallery": "గ్యాలరీ నుండి",
    "useCamera": "కెమెరా ఉపయోగించండి",
    "describePlaceholder": "సమస్యను వివరించండి (ఉదా., పసుపు మచ్చలు, వాడిపోతున్న ఆకులు)",
    "analyzeButton": "పంట ఆరోగ్యాన్ని విశ్లేషించండి",
    "analyzing": "విశ్లేషిస్తోంది...",
    "resultTitle": "AI విశ్లేషణ ఫలితం",
    "upload": "అప్‌లోడ్",
    "voiceNotAvailable": "వాయిస్ ఫీచర్ ఇక్కడ అందుబాటులో లేదు.",
    "startRecording": "రికార్డింగ్ ప్రారంభించండి",
    "stopRecording": "రికార్డింగ్ ఆపండి",
    "speakWeb": "మాట్లాడండి",
    "stopWeb": "ఆపండి",
    "webVoice": "వెబ్ వాయిస్",
    "mobileVoice": "మొబైల్ వాయిస్ → సర్వర్ ట్రాన్స్క్రిప్షన్",
    "failweather": "వాతావరణ డేటాను పొందడం విఫలమైంది",
    "weatherAlert": "వాతావరణ హెచ్చరిక",
    "rainAlert": "రాబోయే 3 రోజుల్లో వర్షం కురిసే అవకాశం ఉంది. నీటిపారుదలని సర్దుబాటు చేయడం గురించి ఆలోచించండి.",
    "fetchingLocation": "స్థానాన్ని పొందుతోంది...",
    "loadingWeather": "వాతావరణ డేటా లోడ్ అవుతోంది...",
    "unknownLocation": "తెలియని స్థానం",
    "locationPermissionDenied": "స్థానాన్ని యాక్సెస్ చేయడానికి అనుమతి నిరాకరించబడింది. డిఫాల్ట్ స్థానాన్ని చూపుతోంది.",
    "couldNotGetLocation": "ప్రస్తుత స్థానాన్ని పొందలేకపోయాము. డిఫాల్ట్ చూపుతోంది.",
    "permissionRequired": "అనుమతి అవసరం",
    "errorTitle": "లోపం",
    "couldNotFetchLocation": "ప్రస్తుత స్థానాన్ని పొందలేకపోయాము.",
    "enterLocationTitle": "స్థానాన్ని నమోదు చేయండి",
    "enterCityName": "దయచేసి నగరం పేరును నమోదు చేయండి:",
    "notFoundTitle": "కనుగొనబడలేదు",
    "couldNotFindLocation": "స్థానాన్ని కనుగొనలేకపోయాము: ",
    "failedToSearchLocation": "స్థానం శోధన విఫలమైంది.",
    "successTitle": "విజయం",
    "fileSelected": "ఫైల్ ఎంచుకోబడింది: ",
    "cameraAccessRequired": "ఫోటో తీయడానికి కెమెరా పర్మిషన్ అవసరం.",
    "photoCaptured": "ఫోటొ క్యాప్చర్ చేయబడింది!",
    "missingImage": "దయచేసి విశ్లేషించే ముందు చిత్రాన్ని అప్‌లోడ్ చేయండి.",
    "grantPermission": "దయచేసి కెమెరా/లైబ్రరీ అనుమతిని ఇవ్వండి.",
    "grantMicPermission": "దయచేసి మైక్రోఫోన్ అనుమతిని ఇవ్వండి.",
    "camera1": "కెమెరా",
    "welcome": "స్వాగతం",
    "soilProperties": "మట్టి లక్షణాలు",
    "soilColor": "మట్టి రకం",
    "selectSoilColor": "మట్టి రకాన్ని ఎంచుకోండి",
    "acidic": "ఆమ్లం",
    "neutral": "తటస్థం",
    "alkaline": "క్షారం",
    "sulfur": "సల్ఫర్ (S)",
    "zinc": "జింక్ (Zn)",
    "weatherInfo": "వాతావరణ సమాచారం",
    "fetchWeather": "లైవ్ వాతావరణ డేటాను పొందండి",
    "fetchingWeather": "పొందుతోంది...",
    "currentSeason": "ప్రస్తుత సీజన్",
    "selectCurrentSeason": "ప్రస్తుత సీజన్‌ను ఎంచుకోండి",
    "climateData": "వాతావరణ డేటా",
    "groundwaterLevel": "భూగర్భ జల స్థాయి",
    "selectGroundwater": "భూగర్భ జల స్థాయిని ఎంచుకోండి",
    "cloudCoverage": "క్లౌడ్ కవరేజ్",
    "surfacePressure": "ఉపరితల పీడనం",
    "farmDetails": "వ్యవసాయ వివరాలు",
    "enterLandSize": "ఎకరాలో భూమి పరిమాణాన్ని నమోదు చేయండి",
    "submit": "డేటాను సమర్పించండి & సిఫార్సులను పొందండి",
    "listening": "వింటున్నాను...",
    "voiceInstructions": "ఇలా చెప్పడానికి ప్రయత్నించండి: \"నత్రజని 70 కి మరియు ఉష్ణోగ్రత 25 కి సెట్ చేయండి\"",
    "soilColorAlluvial": "ఒండ్రు",
    "soilColorBlack": "నల్ల రేగడి",
    "soilColorRed": "ఎర్రని",
    "seasonMonsoon": "వర్షాకాలం (ఖరీఫ్)",
    "seasonSummer": "వేసవి కాలం (జైద్)",
    "seasonWinter": "శీతాకాలం (రబీ)",
    "groundwaterHigh": "అధికం",
    "groundwaterMedium": "మధ్యస్థం",
    "groundwaterLow": "తక్కువ",
    "loading": "లోడ్ అవుతోంది...",
    "error": "లోపం",
    "success": "విజయం",
    "retry": "మళ్లీ ప్రయత్నించండి",
    "back": "వెనుకకు",
    "next": "తరువాత",
    "goToDiseaseDetection": "వ్యాధి గుర్తింపుకు వెళ్లండి",
    "identifyCropDiseases": "పంట వ్యాధులను తక్షణమే గుర్తించండి",
    "soilCondition": "మట్టి పరిస్థితి",
    "filterRecommendations": "సూచనలను ఫిల్టర్ చేయండి",
    "allCrops": "అన్ని పంటలు",
    "shortDuration": "స్వల్ప వ్యవధి",
    "fertilizerRecommendations": "ఎరువుల సిఫార్సులు",
    "forCrop": "కోసం",
    "productionBoost": "ఉత్పత్తి పెంపు",
    "diseaseControl": "వ్యాధి నియంత్రణ",
    "weedManagement": "కలుపు నిర్వహణ (గడ్డి మందు)",
    "dosage": "మోతాదు",
    "notes": "గమనికలు",
    "close": "మూసివేయి",
    "weatherForecast": "వాతావరణ సూచన",
    "updated": "నవీకరించబడింది",
    "alertsAndRecommendations": "హెచ్చరికలు & సిఫార్సులు",
    "overcast": "మేఘావృతం",
    "low": "తక్కువ",
    "moderate": "మోస్తరు",
    "high": "అధికం",
    "veryHigh": "చాలా ఎక్కువ",
    "extreme": "తీవ్రమైన",
    "october": "అక్టోబర్",
    "retreatingMonsoon": "తిరోగమన రుతుపవనాలు",
    "retreatingMonsoonDesc": "ఈశాన్య రుతుపవనాలు బంగాళాఖాతం నుండి భారీ వర్షపాతం మరియు తుఫాను కార్యకలాపాల ప్రమాదాన్ని తెస్తాయి.",
    "november": "నవంబర్",
    "activeCyclone": "క్రియాశీల తుఫాను సీజన్",
    "activeCycloneDesc": "ఈ ప్రాంతానికి పీక్ తుఫాను సీజన్. సంభావ్య తుఫానులు మరియు భారీ గాలుల కోసం నవీకరణలను ట్రాక్ చేయండి.",
    "december": "డిసెంబర్",
    "coolPleasant": "చల్లని & ఆహ్లాదకరమైన",
    "coolPleasantDesc": "రుతుపవనాల కార్యకలాపాలు తగ్గుముఖం పడతాయి, చల్లని, పొడి శీతాకాల వాతావరణానికి మారుతాయి.",
    "heavyRain": "భారీ వర్షం",
    "potentialFloods": "సంభావ్య వరదలు",
    "storms": "తుఫానులు",
    "morningFog": "ఉదయం పొగమంచు",
    "rainExpected": "వర్షం ఆశించబడుతోంది",
    "rainExpectedDesc": "బుధవారం భారీ వర్షపాతం అంచనా వేయబడింది. నీటిపారుదల షెడ్యూల్ను సర్దుబాటు చేయండి మరియు సున్నితమైన పంటలను రక్షించండి.",
    "highUV": "అధిక UV సూచిక",
    "highUVDesc": "ఈ వారాంతంలో UV స్థాయిలు ఎక్కువగా ఉంటాయి. కార్మికులకు తగిన రక్షణ కల్పించండి మరియు షేడ్ కవర్లను పరిగణించండి.",
    "optimalConditions": "శ్రేష్టమైన పెరుగుదల పరిస్థితులు",
    "optimalConditionsDesc": "చాలా పంటలకు ఉష్ణోగ్రత మరియు తేమ స్థాయిలు అనువైనవి. నాటడం మరియు క్షేత్ర కార్యకలాపాలకు మంచి సమయం.",
    "title1": "చారిత్రక డేటా",
    "subtitle1": "కాలక్రమేణా మీ వ్యవసాయ పనితీరును ట్రాక్ చేయండి మరియు విశ్లేషించండి",
    "overview": "అవలోకనం",
    "records": "రికార్డులు",
    "analytics": "విశ్లేషణలు",
    "totalArea": "మొత్తం సాగు చేసిన విస్తీర్ణం",
    "avgYield": "సగటు దిగుబడి / ఎకరం",
    "totalProd": "మొత్తం ఉత్పత్తి",
    "cropsRecorded": "రికార్డ్ చేయబడిన పంటలు",
    "bestCrops": "ఉత్తమ పనితీరు కనబరుస్తున్న పంటలు",
    "quintals": "క్వింటాళ్లు",
    "acres": "ఎకరాలు",
    "yieldPerAcre": "q/ఎకరం",
    "sown": "విత్తు వేసిన",
    "harvested": "కోతకు వచ్చిన",
    "area": "విస్తీర్ణం",
    "irrigationEff": "నీటిపారుదల సామర్థ్య విశ్లేషణ",
    "yieldPerformance": "పంట ద్వారా దిగుబడి పనితీరు",
    "rainfallTrend": "వర్షపాతం Vs పంట దిగుబడి ట్రెండ్",
    "crop": "పంట",
    "yield": "దిగుబడి (q)",
    "avgPH": "సగటు pH",
    "avgNitro": "సగటు నత్రజని (kg/ha)",
    "market_title": "పంట & మార్కెట్ ధరలు",
    "market_subtitle": "ప్రస్తుత మార్కెట్ ధరలు మరియు అమ్మకపు సిఫార్సులను పొందండి",
    "market_cropType": "పంట రకం",
    "market_harvestQuantity": "పంట పరిమాణం (క్వింటాళ్ళు)",
    "market_getCurrentPrices": "ప్రస్తుత ధరలను పొందండి",
    "market_priceAnalysis": "ధరల విశ్లేషణ",
    "market_recommendedPrice": "సిఫార్సు చేయబడిన విక్రయ ధర",
    "market_currentPrice": "ప్రస్తుత మార్కెట్ ధర",
    "market_weekHigh": "వారం గరిష్ట ధర",
    "market_weekLow": "వారం కనిష్ట ధర",
    "market_trend": "సరళి",
    "market_totalValue": "మొత్తం విలువ",
    "market_sellNow": "ఇప్పుడే అమ్మండి",
    "market_waitAdvice": "మంచి ధర కోసం వేచి ఉండండి",
    "market_priceUp": "ధర పెరుగుతోంది",
    "market_priceDown": "ధర తగ్గుతోంది",
    "market_stable": "స్థిరంగా ఉంది",
    "market_bestTime": "అమ్మడానికి ఉత్తమ సమయం",
    "market_waitTime": "2-3 రోజులు వేచి ఉండటానికి పరిగణించండి",
    "market_selectCrop": "ఒక పంటని ఎంచుకోండి",
    "market_enterQuantity": "పరిమాణం నమోదు చేయండి",
    "market_last7Days": "గత 7 రోజుల ధరలు",
    "market_date": "తేదీ",
    "market_price": "ధర",
    "market_recommendation": "అమ్మకం సిఫార్సు",
    "market_rupees": "₹",
    "market_per": "కి",
    "market_quintal": "క్వింటాల్",
    "market_crops": {
        "wheat": "గోధుమ",
        "rice": "వరి",
        "corn": "మొక్కజొన్న",
        "cotton": "పత్తి"
    },
    "loginWelcome": "స్వాగతం",
    "loginAppName": "KrishiMitra",
    "loginSubtitle": "మీ స్మార్ట్ అగ్రికల్చరల్ ఇంటెలిజెన్స్ ప్లాట్‌ఫారమ్",
    "loginEmailSectionTitle": "ఇమెయిల్‌తో లాగిన్ అవ్వండి",
    "loginEmailPlaceholder": "మీ ఇమెయిల్‌ను నమోదు చేయండి",
    "loginPasswordPlaceholder": "మీ పాస్‌వర్డ్‌ను నమోదు చేయండి",
    "loginButtonText": "లాగిన్",
    "loginGoogleButton": "Googleతో కొనసాగండి",
    "loginGuestButton": "అతిథిగా కొనసాగండి",
    "loginForgotPassword": "పాస్‌వర్డ్ మర్చిపోయారా?",
    "loginNoAccount": "ఖాతా లేదా?",
    "loginSignUpLink": "సైన్ అప్ చేయండి",
    "loginOrContinueWith": "లేదా కొనసాగించండి",
    "loginErrorInvalidCredentials": "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్",
    "loginSuccessMessage": "లాగిన్ విజయవంతమైంది!"
},
  hi: {
    // Navigation
    home: "होम",
    enterData: "डेटा दर्ज करें",
    suggestions: "सुझाव",
    history: "इतिहास",
    weather: "मौसम",
    disease: "रोग",
    market: "बाज़ार",
    changeLanguage: "English",
    loginWelcome: "आपका स्वागत है",
    loginAppName: "कृषिमित्र",
    loginSubtitle: "आपका स्मार्ट कृषि बुद्धिमत्ता प्लेटफॉर्म",
    loginEmailSectionTitle: "ईमेल से लॉगिन करें",
    loginEmailPlaceholder: "अपना ईमेल दर्ज करें",
    loginPasswordPlaceholder: "अपना पासवर्ड दर्ज करें",
    loginButtonText: "लॉगिन करें",
    loginGoogleButton: "Google से जारी रखें",
    loginGuestButton: "अतिथि के रूप में जारी रखें",
    loginForgotPassword: "पासवर्ड भूल गए?",
    loginNoAccount: "खाता नहीं है?",
    loginSignUpLink: "साइन अप करें",
    loginOrContinueWith: "या इसके साथ जारी रखें",
    loginErrorInvalidCredentials: "अमान्य ईमेल या पासवर्ड",
    loginSuccessMessage: "लॉगिन सफल!",

    profile: "प्रोफ़ाइल",
    profile_subtitle: "अपना खाता और खेत विवरण प्रबंधित करें",
    user_name: "नाम",
    user_email: "ईमेल",
    user_phone: "फ़ोन",
    user_location: "स्थान",
    farm_info: "खेत की जानकारी",
    farm_size: "खेत का आकार (एकड़)",
    soil_type: "मिट्टी का प्रकार",
    main_crops: "मुख्य फसलें",
    experience: "अनुभव (साल)",
    personal_info: "व्यक्तिगत जानकारी",
    edit_profile: "प्रोफ़ाइल संपादित करें",
    cancel_edit: "रद्द करें",
    save_changes: "परिवर्तन सहेजें",
    logout: "लॉगआउट",
    logout_confirm: "क्या आप वाकई लॉगआउट करना चाहते हैं?",
    cancel: "रद्द करें",
    success_title: "सफल",
    profile_updated: "प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!",
    error_title: "त्रुटि",
    error_saving_profile: "प्रोफ़ाइल सहेजने में विफल।",
    error_loading_profile: "प्रोफ़ाइल लोड करने में त्रुटि।",
    logout_error: "लॉगआउट विफल।",
    loading_profile: "प्रोफ़ाइल लोड हो रही है...",
    user_not_found: "उपयोगकर्ता नहीं मिला।",



    // Dashboard & General UI
    welcomeBack: "वापसी पर स्वागत है! 👋",
    quickAccess: "त्वरित पहुँच",
    smartCropRecommendation: "स्मार्ट फसल सिफारिश प्रणाली",
    smartCropSubtitle:
      "अपनी मिट्टी और मौसम की स्थिति के आधार पर AI-संचालित फसल सुझाव प्राप्त करें",
    uploadPhotoFile: "फोटो/फाइल अपलोड करें",
    uploadSubtitle: "स्वचालित रूप से मिट्टी और मौसम के मूल्यों का पता लगाएं",
    todaysOverview: "आज का अवलोकन",
    viewAnalytics: "एनालिटिक्स देखें",
    analyticsSubtitle: "ऐतिहासिक उपज डेटा और रुझानों की जाँच करें",
    pageTitle: "कृषि डेटा दर्ज करें",
    pageSubtitle:
      "व्यक्तिगत फसल सिफारिशों के लिए अपनी मिट्टी और मौसम की जानकारी प्रदान करें।",
    voice: "आवाज़",
    upload: "अपलोड करें।",
    welcome: "वापसी पर स्वागत है",

    // Weather Details
    title: "मौसम पूर्वानुमान",
    subtitle: "अमरावती, एपी - अपडेट किया गया",
    todaysWeather: "आज का मौसम",
    sevenDayForecast: "7-दिन का पूर्वानुमान",
    feelsLike: "जैसा महसूस होता है",
    uvIndex: "यूवी सूचकांक",
    todaysForecast: "आज का पूर्वानुमान",
    threeMonthOutlook: "3-महीने का दृष्टिकोण",
    climateAverages: "जलवायु औसत",
    alerts: "अलर्ट और सिफारिशें",
    rain: "वर्षा",
    avgTemp: "औसत तापमान",
    annualRainfall: "वार्षिक वर्षा",
    avgHumidity: "औसत नमी",
    growingSeasons: "सर्वश्रेष्ठ बढ़ते मौसम",
    winter: "सर्दी (नवंबर-फरवरी)",
    spring: "बसंत (मार्च-मई)",
    postMonsoon: "मानसून के बाद",
    today: "आज",
    tomorrow: "कल",

    // Soil Properties Card
    soilProperties: "मिट्टी के गुण",
    soilColor: "मिट्टी का प्रकार",
    selectSoilColor: "मिट्टी का प्रकार चुनें",
    phLevel: "पीएच स्तर",
    acidic: "अम्लीय",
    neutral: "तटस्थ",
    alkaline: "क्षारीय",
    nitrogen: "नाइट्रोजन (N)",
    phosphorus: "फॉस्फोरस (P)",
    potassium: "पोटेशियम (K)",
    sulfur: "सल्फर (S)",
    zinc: "जिंक (Zn)",



    // Weather Info Card
    weatherInfo: "मौसम की जानकारी",
    fetchWeather: "लाइव मौसम डेटा प्राप्त करें",
    fetchingWeather: "प्राप्त हो रहा है...",
    currentSeason: "वर्तमान मौसम",
    selectCurrentSeason: "वर्तमान मौसम चुनें",
    humidity: "नमी",
    temperature: "तापमान",
    rainfall: "वर्षा",

    // Climate Data Card
    climateData: "जलवायु डेटा",
    windSpeed: "हवा की गति",
    groundwaterLevel: "भूजल स्तर",
    selectGroundwater: "भूजल स्तर चुनें",
    cloudCoverage: "बादल का आवरण",
    surfacePressure: "सतह का दबाव",

    // Farm Details Card
    farmDetails: "खेत का विवरण",
    landSize: "भूमि का आकार (एकड़)",
    enterLandSize: "एकड़ में भूमि का आकार दर्ज करें",

    // Actions and Modals
    submit: "डेटा सबमिट करें और सिफारिशें प्राप्त करें",
    listening: "सुन रहा है...",
    voiceInstructions:
      'कहने का प्रयास करें: "नाइट्रोजन 70 और तापमान 25 पर सेट करें"',

    // Picker Options
    soilColorAlluvial: "जलोढ़",
    soilColorBlack: "काली",
    soilColorRed: "लाल",
    seasonMonsoon: "मानसून (खरीफ)",
    seasonSummer: "गर्मी (जायद)",
    seasonWinter: "सर्दी (रबी)",
    groundwaterHigh: "उच्च",
    groundwaterMedium: "मध्यम",
    groundwaterLow: "कम",

    // General Navigation/Actions
    goToDiseaseDetection: "रोग पहचान पर जाएँ",
    identifyCropDiseases: "फसल रोगों की तुरंत पहचान करें",
    soilCondition: "मिट्टी की स्थिति",



    // Crop Recommendations
    cropSuggestionsTitle: "फसल सिफारिशें",
    cropSuggestionsSubtitle: "आपके खेत डेटा के आधार पर AI-संचालित सुझाव",
    analyzingData: "आपके खेत डेटा का विश्लेषण किया जा रहा है...",
    soilMatch: "मिट्टी मिलान",
    weatherSuitability: "मौसम उपयुक्तता",
    yieldPotential: "उपज क्षमता",
    duration: "अवधि",
    waterRequirement: "जल आवश्यकता",
    totalYield: "अपेक्षित उपज",
    whyThisCrop: "यह फसल क्यों?",
    matchPercentage: "मिलान",
    highYield: "उच्च",
    mediumYield: "मध्यम",
    lowYield: "कम",
    highWater: "उच्च",
    mediumWater: "मध्यम",
    lowWater: "कम",
    tons: "टन",

    // Form inputs
    soilType: "मिट्टी का प्रकार",
    climateCondition: "जलवायु की स्थिति",
    irrigationAvailable: "सिंचाई उपलब्ध",
    Camera: "कैमरा",

    // Disease Detection
    diseaseTitle: "रोग पहचान",
    diseaseSubtitle:
      "AI-आधारित विश्लेषण के लिए एक फसल छवि अपलोड करें और समस्या का वर्णन करें।",
    uploadPlaceholder: "कोई छवि अपलोड नहीं हुई",
    fromGallery: "गैलरी से",
    useCamera: "कैमरा उपयोग करें",
    describePlaceholder:
      "समस्या का वर्णन करें (जैसे, पत्तियों पर पीले धब्बे, झड़ना)",
    analyzeButton: "फसल स्वास्थ्य विश्लेषण करें",
    analyzing: "विश्लेषण चल रहा है...",
    resultTitle: "AI विश्लेषण परिणाम",

    // Voice commands
    voiceNotAvailable: "यहाँ वॉयस सुविधा उपलब्ध नहीं है।",
    startRecording: "रिकॉर्डिंग शुरू करें",
    stopRecording: "रिकॉर्डिंग बंद करें",
    speakWeb: "बोलें",
    stopWeb: "रोकें",
    webVoice: "वेब वॉयस",
    mobileVoice: "मोबाइल वॉयस → सर्वर ट्रांसक्रिप्शन",

    // Alerts & Permissions
    failweather: "मौसम का डाटा प्राप्त करने में विफल रहा।",
    weatherAlert: "मौसम चेतावनी",
    rainAlert:
      "अगले 3 दिनों में बारिश की उम्मीद है। सिंचाई को समायोजित करने पर विचार करें।",
    fetchingLocation: "स्थान प्राप्त हो रहा है...",
    loadingWeather: "मौसम डेटा लोड हो रहा है...",
    unknownLocation: "अज्ञात स्थान",
    locationPermissionDenied:
      "स्थान की अनुमति नहीं दी गई। डिफ़ॉल्ट स्थान दिखाया जा रहा है।",
    couldNotGetLocation:
      "वर्तमान स्थान प्राप्त नहीं हो सका। डिफ़ॉल्ट दिखाया जा रहा है।",
    permissionRequired: "अनुमति आवश्यक",
    errorTitle: "त्रुटि",
    couldNotFetchLocation: "वर्तमान स्थान प्राप्त नहीं हो सका।",
    enterLocationTitle: "स्थान दर्ज करें",
    enterCityName: "कृपया शहर का नाम दर्ज करें:",
    notFoundTitle: "नहीं मिला",
    couldNotFindLocation: "स्थान नहीं मिल सका: ",
    failedToSearchLocation: "स्थान खोजने में विफल।",
    successTitle: "सफलता",
    fileSelected: "फ़ाइल चयनित: ",
    cameraAccessRequired: "फोटो लेने के लिए कैमरे तक पहुंच आवश्यक है।",
    photoCaptured: "फोटो सफलतापूर्वक लिया गया!",
    missingImage: "कृपया विश्लेषण करने से पहले एक छवि अपलोड करें।",
    grantPermission: "कृपया कैमरा/लाइब्रेरी अनुमति दें।",
    grantMicPermission: "कृपया माइक्रोफोन अनुमति दें।",

    // General
    loading: "लोड हो रहा है...",
    error: "त्रुटि",
    success: "सफलता",
    retry: "पुनः प्रयास",
    back: "वापस",
    next: "आगे",
    weatherForecast: "मौसम का पूर्वानुमान",
    updated: "अपडेट किया गया",

    alertsAndRecommendations: "अलर्ट और सिफारिशें",
    // Data-specific translations
    overcast: "घने बादल",
    low: "कम",
    moderate: "मध्यम",
    high: "उच्च",
    veryHigh: "बहुत उच्च",
    extreme: "अत्यधिक",
    // Outlooks
    october: "अक्टूबर",
    retreatingMonsoon: "लौटता मानसून",
    retreatingMonsoonDesc:
      "उत्तर-पूर्वी मानसून बंगाल की खाड़ी से भारी वर्षा और चक्रवाती गतिविधि का खतरा लाता है।",
    november: "नवंबर",
    activeCyclone: "सक्रिय चक्रवात का मौसम",
    activeCycloneDesc:
      "क्षेत्र के लिए चरम चक्रवात का मौसम। संभावित तूफानों और तेज हवाओं के लिए अपडेट की निगरानी करें।",
    december: "दिसंबर",
    coolPleasant: "ठंडा और सुखद",
    coolPleasantDesc:
      "मानसूनी गतिविधि समाप्त हो जाती है, ठंडे, शुष्क सर्दियों के मौसम में परिवर्तित हो जाती है।",
    heavyRain: "भारी वर्षा",
    potentialFloods: "संभावित बाढ़",
    storms: "तूफ़ान",
    morningFog: "सुबह का कोहरा",
    // Alerts
    rainExpected: "बारिश की उम्मीद",
    rainExpectedDesc:
      "बुधवार को भारी बारिश की भविष्यवाणी की गई है। सिंचाई कार्यक्रम को समायोजित करने और संवेदनशील फसलों की सुरक्षा पर विचार करें।",
    highUV: "उच्च यूवी इंडेक्स",
    highUVDesc:
      "इस सप्ताह के अंत में यूवी का स्तर उच्च रहेगा। श्रमिकों के लिए पर्याप्त सुरक्षा सुनिश्चित करें और शेड कवर पर विचार करें।",
    optimalConditions: "इष्टतम बढ़ती स्थितियाँ",
    optimalConditionsDesc:
      "अधिकांश फसलों के लिए तापमान और आर्द्रता का स्तर आदर्श है। रोपण और खेत की गतिविधियों के लिए अच्छा समय है।",
    title1: "ऐतिहासिक डेटा",
    subtitle1: "समय के साथ अपने खेत के प्रदर्शन को ट्रैक और विश्लेषण करें",
    overview: "अवलोकन",
    records: "रिकॉर्ड्स",
    analytics: "विश्लेषिकी",
    totalArea: "कुल खेती का क्षेत्र",
    avgYield: "औसत उपज / एकड़",
    totalProd: "कुल उत्पादन",
    cropsRecorded: "दर्ज फसलें",
    bestCrops: "सर्वश्रेष्ठ प्रदर्शन करने वाली फसलें",
    quintals: "क्विंटल",
    acres: "एकड़",
    yieldPerAcre: "q/एकड़",
    sown: "बुवाई",
    harvested: "कटाई",
    area: "क्षेत्र",
    irrigationEff: "सिंचाई दक्षता विश्लेषण",
    yieldPerformance: "फसल द्वारा उपज प्रदर्शन",
    rainfallTrend: "वर्षा बनाम फसल उपज की प्रवृत्ति",
    crop: "फसल",

    yield: "उपज (q)",

    avgPH: "औसत पीएच",
    avgNitro: "औसत नाइट्रोजन (किग्रा/हेक्टेयर)",
    market_title: "फसल और बाजार भाव",
    market_subtitle: "वर्तमान बाजार भाव और बिक्री सुझाव प्राप्त करें",
    market_cropType: "फसल का प्रकार",
    market_harvestQuantity: "फसल की मात्रा (क्विंटल)",
    market_getCurrentPrices: "वर्तमान भाव देखें",
    market_priceAnalysis: "भाव विश्लेषण",
    market_recommendedPrice: "सुझावित बिक्री भाव",
    market_currentPrice: "वर्तमान बाजार भाव",
    market_weekHigh: "सप्ताह उच्च",
    market_weekLow: "सप्ताह निम्न",
    market_trend: "ट्रेंड",
    market_totalValue: "कुल मूल्य",
    market_sellNow: "अभी बेचें",
    market_waitAdvice: "बेहतर भाव का इंतजार करें",
    market_priceUp: "भाव बढ़ रहा है",
    market_priceDown: "भाव गिर रहा है",
    market_stable: "स्थिर",
    market_bestTime: "बेचने का सबसे अच्छा समय",
    market_waitTime: "2-3 दिन प्रतीक्षा करने पर विचार करें",
    market_selectCrop: "एक फसल चुनें",
    market_enterQuantity: "मात्रा दर्ज करें",
    market_last7Days: "पिछले 7 दिनों के भाव",
    market_date: "तारीख",
    market_price: "भाव",
    market_recommendation: "बिक्री की सिफारिश",
    market_rupees: "₹",
    market_per: "प्रति",
    market_quintal: "क्विंटल",
    market_crops: {
      wheat: "गेहूं",
      rice: "चावल",
      corn: "मक्का",
      cotton: "कपास",
    },

    // --- Crop Recommendations Page ---
    filterRecommendations: "सिफारिशें फ़िल्टर करें",
    allCrops: "सभी फसलें",
    shortDuration: "कम अवधि",
    fertilizerRecommendations: "उर्वरक की सिफारिशें",
    forCrop: "के लिए",
    productionBoost: "उत्पादन बढ़ावा",
    diseaseControl: "रोग नियंत्रण",
    weedManagement: "घास नियंत्रण (घास मार)",
    dosage: "खुराक",
    notes: "नोट्स",
    close: "बंद करें",

    // General
    overallGood: "कुल मिलाकर: अच्छा",
    camera1: "कैमरा",
  },
};

export type Language = "en" | "hi" | "te";
export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: typeof translations.en;
}

export const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>("en");

  const toggleLanguage = useCallback(() => {
    setLanguage((prev) => {
      if (prev === "en") return "hi";
      if (prev === "hi") return "te";
      return "en";
    });
  }, []);

  const t = translations[language];

  const value: LanguageContextType = {
    language,
    setLanguage,
    toggleLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

